const Vector2 BLOCK_HALF = { BOARD_BLOCK_WIDTH/2, BOARD_BLOCK_WIDTH/2 };

const Vector2 BLOCKS_POS[BOARD_BLOCKS_COUNT] = {
    {
        0, 0
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2), 0
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1), 0
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2)
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1)
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1)
    },
    {
        0, BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-1)
    },
    {
        0, BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2)
    },

    // Middle square
    {
        BOARD_BLOCK_WIDTH,
        BOARD_BLOCK_WIDTH,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
        BOARD_BLOCK_WIDTH,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
        BOARD_BLOCK_WIDTH,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
    },
    {
        BOARD_BLOCK_WIDTH,
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-2),
    },
    {
        BOARD_BLOCK_WIDTH,
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
    },

    // Inner  square
    {
        BOARD_BLOCK_WIDTH*2,
        BOARD_BLOCK_WIDTH*2,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
        BOARD_BLOCK_WIDTH*2,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
        BOARD_BLOCK_WIDTH*2,
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
    },
    {
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
    },
    {
        BOARD_BLOCK_WIDTH*2,
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT-3),
    },
    {
        BOARD_BLOCK_WIDTH*2,
        BOARD_BLOCK_WIDTH*(BOARD_ROW_BLOCK_COUNT/2),
    }
};
